name: 'Store evaluation'
description: 'This action store evaluations from Tryber projects.'
inputs:
  evaluation-data:
    description: 'JSON with structure below in the base64 format'
    required: true
  environment:
    description: 'Environment'
    required: true
    default: 'development'
  pr-number:
    description: 'Pull Request number that trigger build'
    required: true
runs:
  using: 'composite'
  steps:
    - id: job
      shell: bash
      run: ${{ github.action_path }}/store.sh
      env:
        EVALUATION_DATA: ${{ inputs.evaluation-data }}
        ENVIRONMENT: ${{ inputs.environment }}
        PR_NUMBER: ${{ inputs.pr-number }}
