name: "Store evaluation"
description: "Essa action salva avaliações de projetos da Trybe."

inputs:
  evaluation-data:
    description: "JSON contendo os resultados do avaliador, no formato base64"
    required: true
  environment:
    description: "Ambiente para qual a avaliação será enviada"
    required: true
    default: "development"
  commit_hash:
    description: "Hash do commit que originou a avaliação"
    required: true

runs:
  using: "composite"
  steps:
    - id: job
      shell: bash
      run: ${{ github.action_path }}/store.sh
      env:
        EVALUATION_DATA: ${{ inputs.evaluation-data }}
        ENVIRONMENT: ${{ inputs.environment }}
        COMMIT_HASH: ${{ inputs.commit_hash }}
