name: "Store evaluation"
description: "Essa action salva avaliações de projetos da Trybe."

inputs:
  evaluation-data:
    description: "JSON contendo os resultados do avaliador, no formato base64"
    required: true
  environment:
    description: "Ambiente para qual a avaliação será enviada"
    required: true
    default: "development"
  token:
    description: "GitHub token do projeto"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Nodejs 16
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - shell: bash
      run: npm install --prefix ${{ github.action_path }}

    - name: Run store-evaluation
      run: node ${{ github.action_path }}/index.mjs 
      shell: bash
      env:
        EVALUATION_DATA: ${{ inputs.evaluation-data }}
        ENVIRONMENT: ${{ inputs.environment }}
        TOKEN: ${{ inputs.token }}
        COMMIT_HASH: ${{ github.event.pull_request.head.sha }}
        GH_USERNAME: ${{ github.event.pull_request.user.login }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

    - name: Run evaluation-feedback
      uses: betrybe/evaluation-feedback-action@v1.0.0
      with: 
        evaluation-data: ${{ inputs.evaluation-data }}
        token: ${{ inputs.token }}
        project_url: ${{ env.PROJECT_URL }}
